#ifndef LOG_CONFIG_H
#define LOG_CONFIG_H

#define ENABLE_LOGGING

#define LOG_LEVEL_NONE  0
#define LOG_LEVEL_ERROR 1
#define LOG_LEVEL_WARN  2
#define LOG_LEVEL_INFO  3
#define LOG_LEVEL_DEBUG 4

#define CURRENT_LOG_LEVEL LOG_LEVEL_DEBUG

#define LOG_OUTPUT_CONSOLE 0
#define LOG_OUTPUT_FILE 1
#define LOG_OUTPUT_TARGET LOG_OUTPUT_CONSOLE
#define LOG_FILE_NAME "app.log"

#define LOG_SHOW_TIMESTAMP 1
#define LOG_SHOW_FILE_LINE 1
#define LOG_SHOW_FUNC_NAME 1

#endif
